apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: roboshop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
    project: roboshop
    tier: app
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
     app: payment
     project: roboshop
     tier: app
  template: #pod definition
    metadata:
      labels: #these labels are pods labels
        app: payment
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payment
        image: nanda1805/payment:v1
        imagePullPolicy: Always #Always, IfNotPresent, Never it will pull the image from the docker hub
        envFrom:
        - secretRef:
            name: payment-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # Service Port
      targetPort: 8080 # container Port
