apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
    REDIS_HOST: "redis"
    CATALOGUE_HOST: "catalogue"
    CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    project: roboshop
    tier: app
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
     app: cart
     project: roboshop
     tier: app
  template: #pod definition
    metadata:
      labels: #these labels are pods labels
        app: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: nanda1805/cart:v1
        imagePullPolicy: Always #Always, IfNotPresent, Never it will pull the image from the docker hub
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    app: cart
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # Service Port
      targetPort: 8080 # container Port
