apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: database
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
     app: mysql
     project: roboshop
     tier: database
  template: #pod definition
    metadata:
      labels: #these labels are pods labels
        app: mysql
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mysql
        image: nanda1805/mysql:v1
        imagePullPolicy: Always #Always, IfNotPresent, Never it will pull the image from the docker hub
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 3306 # Service Port
      targetPort: 3306 # container Port







# ENV MYSQL_ROOT_PASSWORD=RoboShop@1 \
#     MYSQL_DATABASE=cities \
#     MYSQL_USER=shipping \
#     MYSQL_PASSWORD=RoboShop@1